### ISSUE TITLE
Ordinal 242 error.

### ISSUE THREAD

**Issue by SuperiorLegend** [dunnousername/yanderifier#3]
I just downloaded v2.0.3 and says it has a potential fix for this error. Seems to not fix it for my case. Any solutions?

**Comment by dunnousername** [comment]
Rereading old issues now; this is a common issue  but unfortunately, despite my attempts, it doesn't look like it can be fixed in my code. See [here](https://conda.io/projects/conda/en/latest/user-guide/troubleshooting.html#numpy-mkl-library-load-failed). I've talked to other devs and it seems to be an issue that cannot be fixed due to quirks in how Windows handles paths.
