### ISSUE TITLE
Cannot install

### ISSUE THREAD

**Issue by M1ghty-boy** [dunnousername/yanderifier#63]
Whenever i try to install it fails, here's the log:
```
Using existing install executable
Using existing fomm.zip
Using existing first-order-motion-model install
Using existing .\yanderify\checkpoint.tar
starting post-install script
The system cannot find the path specified.
The system cannot find the path specified.
miniconda already installed
The system cannot find the path specified.
Installation is almost done! doing some sanity checks
Failed a sanity check. You should tell the devs about this!
Traceback (most recent call last):
  File "E:\Downloads\yanderifier-4.0.3-stable\install\postinstall.py", line 10, in <module>
    raise e
  File "E:\Downloads\yanderifier-4.0.3-stable\install\postinstall.py", line 4, in <module>
    import numpy as np
ModuleNotFoundError: No module named 'numpy'
cp : Cannot find path 'E:\Downloads\yanderifier-4.0.3-stable\miniconda\pkgs' because it does not exist.
At E:\Downloads\yanderifier-4.0.3-stable\install\windows\install.ps1:73 char:1
+ cp .\miniconda\pkgs\ffmpeg-*\Library\bin\* .\miniconda\Library\bin\
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (E:\Downloads\ya...\miniconda\pkgs:String) [Copy-Item], ItemNotFoundExce
   ption
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.CopyItemCommand
```

**Comment by Animan8000** [comment]
Looks like you were downloading the source code instead of an official release? You wanna use a full release of Yanderify and it should work probably fine (with including the [**checkpoint**](https://github.com/dunnousername/yanderifier/releases/download/model/checkpoint.tar), etc.). Also aside of that, the main branch's source code uses the old version 3 of Yanderify which was unfortunately quite buggy. You can get the newest official release [**here**](https://github.com/dunnousername/yanderifier/releases/download/v4.0.3-stable/yanderify.zip).

Good luck!

**Comment by M1ghty-boy** [comment]
when using the version linked, i just get this before the window closes (took me about 5 attempts to get the screenshot before it closed)
![image](https://user-images.githubusercontent.com/29181101/105175837-5a78a500-5b1c-11eb-9d81-b6b87b32cab8.png)

**Comment by Animan8000** [comment]
You need to download the checkpoint as well, [**here**](https://github.com/dunnousername/yanderifier/releases/download/model/checkpoint.tar).

And put it in the same folder as the Yanderify.exe file. Don't extract the checkpoint.tar file by the way! For any additional questions, feel free to ping me in Discord since I saw your message. Also for future references: try starting the exe file over the command prompt when something goes wrong and Yanderify closes instantly, making it easier to screenshot an error.

**Comment by M1ghty-boy** [comment]
thanks i got it working, having some cuda issues now after updating drivers but I'll close this issue and make a new one about that
